### ISSUE TITLE
Suggestion: Allow searching by AppID

### ISSUE THREAD

**Issue by andrewbaker-uk** [jsnli/Samira#1]
### Description

I believe allowing searching by App ID will allow games which don't appear when searched for accessible to be found

### Expected Behavior

When searching for Sid Meier's Civilization VI no results are returned, which follows the same behavior as SamRewritten. 

![image](https://github.com/user-attachments/assets/0d36c74c-4f40-4959-ae6e-393a833bb26e)

However when using the App Id of Civilization VI I'm able to then relock the achievements as required

### Impact

This would allow people to use App IDs if the game was not initially found using the Game Name

**Comment by jsnli** [comment]
A fix is available in the newest release  [v0.3.0](https://github.com/jsnli/Samira/releases/tag/v0.3.0).

![20241113_08h06m06s_grim](https://github.com/user-attachments/assets/e74e46f4-7f4f-4c0c-bbdc-6c77e8d997ca)

This issue seemed to be caused by a special symbol ® and a locked scroll. You should be able to locate the game now. You'll also be able to launch directly through AppID or search for the game via AppID. Thanks for reporting this issue.

**Comment by andrewbaker-uk** [comment]
Thank you for implementing :+1:
