### ISSUE TITLE
Wayland support [No XWayland]

### ISSUE THREAD

**Issue by Twig6943** [jsnli/Samira#4]
Idk what this app uses, (doesnt seem to be gtk/qt) regardless could u add wayland support?

**Comment by Twig6943** [comment]
Also very amazing project

**Comment by jsnli** [comment]
Are you encountering any issues? Wayland is supported by Tauri.

**Comment by Twig6943** [comment]
@jsnli  na but the project runs via XWayland even though I'm on wayland 

https://github.com/user-attachments/assets/8c51a2df-9ef9-421d-8908-d38c7d25d579

**Comment by jsnli** [comment]
Tauri unfortunately currently forces X11/XWayland on AppImages due to [gtk crashes](https://github.com/tauri-apps/tauri/issues/8541#issuecomment-1877251129). I'm not able to provide a solution for this and we'll need to wait for an official fix from the Tauri developers. I'll look to double check with them in the coming week. Thanks for your patience.

**Comment by Twig6943** [comment]
also @jsnli I've got Samira added to AM pkg manager's default repository.
https://github.com/ivan-hc/AM/issues/1133

**Comment by Twig6943** [comment]
@jsnli what about packaging as flatpak?

**Comment by jsnli** [comment]
If Steam is installed through Flatpak, Samira won't be able to find steam and will fail to start a client. Ideally, I'd like to investigate the issue to see if this can be resolved before packaging up Samira itself. That being said I'm open to the idea once we get closer to a v1.0.0 release.
